In [1]:
import numpy as np

In [2]:
x = [[7,2],[3,4],[8,10]] #2D array
a = np.array(x)
print(x)
print(a)

[[7, 2], [3, 4], [8, 10]]
[[ 7  2]
 [ 3  4]
 [ 8 10]]


In [6]:
print(a[2][1])
print(a[2,1])

10
10


In [8]:
x = np.array([2,3,4,5]) #1D array
y = np.array ([(1,2),(3,4),(5,6)]) #2D array 
c = np.array([(1.5,2.5,3.5,4.5),(5.5,6.5,7.5,8.5)] #3D arrary
print(x)
print(y)

[2 3 4 5]
[[1 2]
 [3 4]
 [5 6]]


In [15]:
print(x[2])
print(y[1,1])
print(x[0:2])
print(y[1:3,0:2]) #row 1 & 2, col 0 

4
4
[2 3]
[[3]
 [5]]


In [16]:
#Create columns 
# Create a 3x4 2-d array, with initial value zero 
a = np.zeros((3,4))
print(a)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
# Create a 2x3x4 3-d array with initial value one
b = np.ones((2,3,4))
print(b)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [22]:
# numpy.arange(start,stop,step)

# Create an array that starts from zero and ends at 8
a = np.arange(0,9)  
print(a)

# Create array that starts from 10 and ends at 19 with interval 2
c = np.arange(10,20,2)
print(c)

# Create an array that contains the dates in month of Aug 2017
d = np.arange('2017-08-01','2017-09-01',dtype='datetime64')
print(d)


[0 1 2 3 4 5 6 7 8]
[10 12 14 16 18]
['2017-08-01' '2017-08-02' '2017-08-03' '2017-08-04' '2017-08-05'
 '2017-08-06' '2017-08-07' '2017-08-08' '2017-08-09' '2017-08-10'
 '2017-08-11' '2017-08-12' '2017-08-13' '2017-08-14' '2017-08-15'
 '2017-08-16' '2017-08-17' '2017-08-18' '2017-08-19' '2017-08-20'
 '2017-08-21' '2017-08-22' '2017-08-23' '2017-08-24' '2017-08-25'
 '2017-08-26' '2017-08-27' '2017-08-28' '2017-08-29' '2017-08-30'
 '2017-08-31']


In [23]:
# numpy.linspace(start,stop,num)

# Create array that starts with 0 and ends at 2# with 9 samples in between
d = np.linspace(0,2,9)
print(d)


[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [24]:
# Create a constant array with a specified value# numpy.full(shape, fill_value)
e = np.full((2,2),7)
print(e)

# Create a 2x2 identity matrix
f = np.eye(2)
print(f)

[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]


In [25]:
# Create a 2x2 array with random floats in the interval 0.0 to 1.0 
g = np.random.random((2,2))
print(g)



# Create a 3x2x4 array with random numbers# between 10 and 50 (not including 50)
h = np.random.randint(10,50,(3,2,4))
print(h)


[[0.96370997 0.35196373]
 [0.10431451 0.33295189]]
[[[13 13 12 33]
  [28 38 41 24]]

 [[47 23 30 19]
  [29 23 17 39]]

 [[37 36 12 15]
  [32 12 17 15]]]


In [27]:
# Create 20 numbers from 1 to 20 as a 1-d array
# then reshape this to a 2d array of shape 4x5
a = np.arange(1,21)
print(a)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [31]:
a = np.arange(1,21).reshape(4,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [33]:
#input different ndarrays into 1 single ndarray
#Criteria, all have to be the same number of co

c1 = np.array([1,2,3,4,5])
c2 = np.arange(2,21,2)
c3 = np.random.randint(1,100,10)

c = np.array([c1,c2,c3])
print(c) 

[array([1, 2, 3, 4, 5]) array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])
 array([65, 97, 75, 42, 34, 57, 28, 73, 16, 75])]


In [43]:
#boolean indexing 

x = np.array ([4,9,2,67.80,70])
b = [True, True, False, False, False, True]
print(x,b) 
print(x(b))

[ 4.   9.   2.  67.8 70. ] [True, True, False, False, False, True]


TypeError: 'numpy.ndarray' object is not callable

In [44]:
x = np.array ([5,6,3,4,9,1,7])
b = x > 5
print(b)

#remove all values from x that are less than 6 


[False  True False False  True False  True]


In [46]:
#remove all values from x that are less than 6 
x = np.array ([5,6,3,4,9,1,7])
x = x[x >5]
print(x)

[6 9 7]


In [48]:
z = y [y%2]
y = [2,4,5,6]
print(z)

TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [49]:
#Sort in ascending order 
x = np.array ([5,3,5,6,2,4,1])
x.sort()
x = x[::-1]
print(x)

[6 5 5 4 3 2 1]


In [50]:
y = np.array ([(7,2),(3,4),(8,10)])
y.sort(axis = 0)
print(y)


[[ 3  2]
 [ 7  4]
 [ 8 10]]


In [51]:
# Reshaped from 1D to 2D
x = np.arange(1,5).reshape(2,2)
y = np.arange(6,12).reshape(3,2)
z = np.arange(8,16).reshape(4,2)

print(x)
print(y)
print(z)
print(np.concatenate((x,y,z)))


[[1 2]
 [3 4]]
[[ 6  7]
 [ 8  9]
 [10 11]]
[[ 8  9]
 [10 11]
 [12 13]
 [14 15]]
[[ 1  2]
 [ 3  4]
 [ 6  7]
 [ 8  9]
 [10 11]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


In [55]:
# Concatenate 2D 

x = np.arange(1,5).reshape(2,2)
y = np.arange(6,12).reshape(2,3)
z = np.arange(8,16).reshape(2,4)

print(x)
print(y)
print(z)
print(np.concatenate((x,y,z),axis=1))


[[1 2]
 [3 4]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[ 1  2  6  7  8  8  9 10 11]
 [ 3  4  9 10 11 12 13 14 15]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [54]:
a = np.array([(1,2,3), (4,5,6)])

b= np.append(a, np.array([(7,8,9)]),axis = 0)
c = np.append(a, np.array([(7,8), (9,10)]),axis = 1)


In [56]:
list1 = [2,2.5, True, 'bye']
a = np.array ([2, 2.5, True, 'bye']) # will be string 
a = np.array ([2, 2.5, True]) # will be float
a = np.array ([2, True]) # will be int

#String --> Float --> int