In [1]:
import numpy as np 

a = np.array([[1,1], [2,2], [3,3]])
print(a)

[[1 1]
 [2 2]
 [3 3]]


In [2]:
#a = np.insert(a, 4, 20) #in a flatten array, 20 will be inserted at index #4 
#print(a)

#a  = np.insert(a, 1, 66, axis=0) #a new row filled with 20 will be inserted at row index #1 
#print(a)



In [3]:
a = np.arange(24).reshape(4,6)
print(a)

a1, a2 = np.split(a,2,axis = 0) #cut half by row 
a1, a2 = np.split(a, 2, axis = 1) #cut half by columns
a1,a2 = np.vsplit(a,2) #cut half by row, same as axis = 0 
a1,a2 = np.hsplit(a,2) #cut half by columns, as as axis = 1 



[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [4]:
d = np.loadtxt('singapore-residents-by-ethnic-group-and-sex-end-june-annual.csv', delimiter=",", skiprows= 1, dtype = [('yr','i4'), ('desc','U30'),('value','i4')], ifna)

SyntaxError: positional argument follows keyword argument (<ipython-input-4-9596f4ad012c>, line 1)

In [5]:
d

NameError: name 'd' is not defined